spring.application.name=api-gateway
server.port=9093

#Eureka configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true
eureka.instance.prefer-ip-address=true 
eureka.instance.hostname=localhost

spring.cloud.gateway.server.webflux.discovery.locator.enabled=false

management.endpoints.web.exposure.include=*
management.endpoint.gateway.access=READ_ONLY


#spring.security.oauth2.resourceserver.jwt.issuer-url=http:localhost:8080
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9096/realms/quizzdev/protocol/openid-connect/certs
logging.level.org.springframework.security=DEBUG

#resilience4j
#difine the number CB should take of to calculate failure rate
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
#define number of calls on halfOpen state
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=2
#define failure failure rate thresold
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
#Define wait duration in open state
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10000

#redis....
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.username=
spring.data.redis.password=
